image: node:16

stages:
  - deploy

cache:
  paths:
    - node_modules
deploy:
  stage: deploy
  script:
    - cd ~ &&
      cd /var/www/light_is_everything_front &&
      git config --global http.proxy http://new.asdfghj.ir:3129 &&
      git reset --hard &&
      git pull &&
      docker compose down &&
      docker compose up -d --build

  only:
    - main
  tags:
    - light_is_everything
