image: node:16

stages:
  - deploy

cache:
  paths:
    - node_modules

deploy:
  stage: deploy
  script:
    - cd ~ &&
      cd /var/www/light_is_everything_front &&
      ssh-agent bash -c 'ssh-add /path/to/your/private/key; git pull' &&
      docker-compose down &&
      docker-compose up

  only:
    - main
  tags:
    - light_is_everything
