name: Deploy_Light_is_everything

on:
  push:
    branches:
      - main

jobs:
  Deploy_Light_is_everything:
    runs-on: self-hosted

    steps:
      - name: Deploy on server
        run: |
          export HTTPS_PROXY=157.90.170.251:3131 &&
          export HTTP_PROXY=157.90.170.251:3131 &&
          cd /var/www/light_is_everything_front/ && 
          git reset --hard &&
          git pull origin main &&
          docker compose up -d --build
