name: Deploy Light_is_everything

on:
  push:
    branches:
      - main

jobs:
  self_hosted_runner_commands:
    runs-on: self-hosted

    steps:
      - name: Deploy on server
        run: |
          cd ~ &&
          cd /var/www/light_is_everything_front/
