name: Deploy Light_is_everything

on:
  push:
    branches:
      - main

jobs:
  self_hosted_runner_commands:
    runs-on: self-hosted

    steps:
      - name: Deploy on server
        run: |
          sudo cd ~ &&
          sudo cd /var/www/light_is_everything_front/ &&
          sudo git reset --hard &&
          sudo git pull &&
          sudo docker compose down &&
          sudo docker compose up -d --build
