name: Self-hosted Runner Command Execution

on:
  push:
    branches:
      - main

jobs:
  self_hosted_runner_commands:
    runs-on: self-hosted

    steps:
      - name: Print Working Directory
        run: |
          pwd

      - name: Display User
        run: |
          whoami
