name: Deploy_Light_is_everything

on:
  push:
    branches:
      - main

jobs:
  Deploy_Light_is_everything:
    runs-on: self-hosted

    steps:
      - name: Deploy on server
        run: |
          cd /var/www/light_is_everything_front/ && 
          git reset --hard &&
          git pull &&
          docker compose down &&
          docker compose up -d --build
